# Generated by Django 5.2.7 on 2025-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
