# Generated by Django 5.2.7 on 2026-05-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="contingency_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="fee_strategy_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly Rate"),
                    ("flat", "Flat Fee"),
                    ("contingency", "Contingency"),
                ],
                default="flat",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="flat_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
